// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_content_delivery_bucket": "freighteasy-20191227081430-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "https://d2z0vvfx53h2io.cloudfront.net",
    "aws_cognito_identity_pool_id": "us-west-2:9d5a6b4f-4151-45a8-939f-610ca0a488a3",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_PeL5S0KIG",
    "aws_user_pools_web_client_id": "1k27fj7srg95m76o2527r8fijf",
    "oauth": {}
};


export default awsmobile;
